package:
  name: bayes_implicit_solvent
  version: "0.0.0"

source:
  path: ../..

build:
  number: 0

requirements:
  host:
    - python
    - setuptools
    - networkx
    - tqdm
    - numpy
    - matplotlib
    - openeye-toolkits
    - openmmtools
    - autograd
    - scipy

  run:
    - python

test:
  requires:
    - pytest
  imports:
    - bayes_implicit_solvent

about:
  home: https://github.com/openforcefield/bayes-implicit-solvent/
  license: MIT License
