package:
  name: bayes_implicit_solvent
  version: "0.0.0"

source:
  path: ../..

build:
  number: 0

requirements:
  build:
    - python
    - setuptools
    - networkx
    - tqdm
    - numpy
    - matplotlib
    - openeye
    - openmmtools
    - autograd
    - scipy

  run:
    - python

test:
  requires:
    - pytest
  imports:
    - bayes_implicit_solvent

about:
  home: add_url_here
  license: MIT License
